import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Suspense } from "react";

const segoeUI = localFont({
    src: '../fonts/SegoeUI-VF.ttf',
    display: 'swap',
    variable: '--font-segoeUi',
});

export const metadata: Metadata = {
    title: "Neuron",
    description: "Generated by create next app",
};

export default function CloudLayout({
    children,
    sidebar, header
}: Readonly<{
    children: React.ReactNode;
    sidebar?: React.ReactNode;
    header?: React.ReactNode;
}>) {
    return (
        <div className={`grid grid-cols-12 grid-rows-12 h-screen bg-[#ebf2fd] ${segoeUI.variable}`}>

            <div className="col-span-12 row-span-1">
                {/* Header Slot */}
                {header}
            </div>

            <div className="col-span-2 row-span-11 row-start-2 border-r border-r-[#b1c2e8]">
                {/* Sidebar Slot */}
                
                <Suspense fallback={<div>Loading sidebar...</div>}>
                    {sidebar}
                </Suspense>
            </div>

            <div className="col-span-10 row-span-11 col-start-3 row-start-2 overflow-y-auto">
                {/* Content */}
                {children}
            </div>

        </div>
    );
}